# Generated by Django 4.0.6 on 2024-04-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='driver_latitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Driver Latitude'),
        ),
        migrations.AddField(
            model_name='users',
            name='driver_longitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Driver Longitude'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Rider', 'Rider'), ('Driver', 'Driver')], max_length=100, null=True, verbose_name='User Type'),
        ),
    ]
