# Generated by Django 4.0.6 on 2024-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverriderequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverriderequest',
            options={'verbose_name': 'DriverRideRequest', 'verbose_name_plural': 'DriverRideRequest'},
        ),
        migrations.AddField(
            model_name='driverriderequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
