# Generated by Django 4.0.6 on 2024-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(blank=True, max_length=256, null=True, verbose_name='Rider')),
                ('driver', models.CharField(blank=True, max_length=256, null=True, verbose_name='Driver')),
                ('pickup_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Pickup Location')),
                ('dropoff_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dropoff Location')),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rides',
                'verbose_name_plural': 'Ride',
            },
        ),
    ]
