# Generated by Django 4.0.6 on 2024-04-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_rides_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='rides',
            name='dropoff_latitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Dropoff Latitude'),
        ),
        migrations.AddField(
            model_name='rides',
            name='dropoff_longitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Dropoff Longitude'),
        ),
        migrations.AddField(
            model_name='rides',
            name='pickup_latitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Pickup Latitude'),
        ),
        migrations.AddField(
            model_name='rides',
            name='pickup_longitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Pickup Longitude'),
        ),
    ]
