# Generated by Django 4.0.6 on 2024-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_rides_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Inprocess', 'Inprocess'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=256, null=True, verbose_name='Status'),
        ),
    ]
